project:
  type: website
  output-dir: C:/Users/zhangtyl.stu/OneDrive - UBC/Documents/GitHub/E-Portfolio

website:
  title: "Tyler Zhang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: publications.qmd
        text: Manhole Mate
      - href: content.qmd
        text: Content & Deliverables

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

