project:
  type: website
  output-dir: C:/Users/zhangtyl.stu/OneDrive - UBC/Documents/GitHub/E-Portfolio

website:
  title: "Tyler Zhang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: Manhole_Mate.qmd
        text: Manhole Mate
      - href: Howe_Sound.qmd
        text: Debris Hotspot Analysis
      - href: DEM.qmd
        text: Lidar Data Analysis

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

