---
title: " "
format: 
  html:
     toc: false
---


# Education

-   <span style="font-size: 18px;">
<strong>University of British Columbia</strong> <br>
Master of Geomatics for Environmental Management<br>
2024-2025<br><br>
</span>

-   <span style="font-size: 18px;">
<strong>University of Victoria</strong><br>
B.Sc in Earth and Ocean Science<br>
2016-2021<br><br>
</span>

-   <span style="font-size: 18px;">
Registered Geoscientist-in-Training (GIT) with EGBC<br>
</span>
<br>



# Work Experience
-   <span style="font-size: 18px;">
<strong>Sonar Data Analyst and Software Developer	</strong> <span style="margin-right: 240px;"></span>   July 2021 – Jan 2024 <br>
AquaCoustic Remote Technologies Inc. <span style="margin-right: 335px;"></span> 
Vancouver, BC

</span> 
<br>

 <span style="font-size: 18px;"><span style="margin-right: 55px;"></span><strong>-</strong> Analyzed field-collected trunk sewer sonar data combined with GIS data to create accurate</span>
  <span style="font-size: 18px;"><span style="margin-right: 65px;"></span>maps, plots, and technical reports for infrastructure condition assessment.</span>

 <span style="font-size: 18px;"><span style="margin-right: 53px;"></span><strong>-</strong> Supported the development and maintenance of GIS databases and optimized data processing</span>
  <span style="font-size: 18px;"><span style="margin-right: 65px;"></span>software to improve efficiency and accuracy</span>
<br><br> <br><br><br>  



-   <span style="font-size: 18px;">
<strong>Research Assistant</strong> <span style="margin-right: 400px;"></span>January 2021 - May 2021<br>
Fisheries and Oceans Canada<span style="margin-right: 430px;"></span> 
Victoria, BC

</span> 
<br>

 
 <span style="font-size: 18px;"><span style="margin-right: 50px;"></span><strong>-</strong>Developed an automated workflow using Python to convert near-real-time CTD oceanographic</span>
  <span style="font-size: 18px;"><span style="margin-right: 55px;"></span>data into TESAC format for Global Telecommunication System (GTS) submission.</span>


 <span style="font-size: 18px;"><span style="margin-right: 50px;"></span><strong>-</strong>Successfully processed and submitted over 200 CTD casts from multiple Pacific surveys,</span>
   <span style="font-size: 18px;"><span style="margin-right: 55px;"></span>enhancing data quality and transmission efficiency.</span>

<br><br> <br><br><br>  


-   <span style="font-size: 18px;">
<strong>Research Assistant</strong> <span style="margin-right: 380px;"></span>   June 2019 - September 2019 <br>
Fisheries and Oceans Canada<span style="margin-right: 435px;"></span> 
Victoria, BC

</span> 
<br>

 
 <span style="font-size: 18px;"><span style="margin-right: 55px;"></span><strong>-</strong>Processed field collected fisheries acoustics data using developed MATLAB scripts. </span>
 

 <span style="font-size: 18px;"><span style="margin-right: 53px;"></span><strong>-</strong> Provided analysis and visualizations for juvenile salmon migration studies.</span>

<br><br>


# Competencies

 <span style="font-size: 18px;"><span style="margin-right: 53px;"></span><strong>Programming:</strong> Proficient in Python, R, and Swift, with expertise in geospatial data analysis and workflow automation. </span><br>
 
   <span style="font-size: 18px;"><span style="margin-right: 53px;"></span><strong>Mobile App Development:</strong> Designed and developed ‘Manhole Mate' software for locating municipal utility infrastructure and retrieving information from geodatabases in Python and iOS (Swift)</span><br>
  
 
 <span style="font-size: 18px;"><span style="margin-right: 53px;"></span><strong>Software:</strong> Proficient in Esri ArcGIS suite (ArcGIS Pro, ArcMap, ArcGIS Online, StoryMaps), QGIS, and CloudCompare. Experienced in map creation, spatial analysis, and 3D point cloud processing.</span><br>
 
  <span style="font-size: 18px;"><span style="margin-right: 53px;"></span><strong>Communication:</strong> Excellent communication skills developed through close collaboration with clients and team members.</span><br>
  



